general {
    col.active_border = rgba(BFA677ff) rgba(010000ff) 45deg
    col.inactive_border = rgba(3C3933ff) rgba(777032ff) 45deg
}

group {
    col.border_active = rgba(3C3933ff) rgba(777032ff) 45deg
    col.border_inactive = rgba(000000cc) rgba(010000cc) 45deg
    col.border_locked_active = rgba(4E4835ff) rgba(615A34ff) 45deg
    col.border_locked_inactive = rgba(010000cc) rgba(010000cc) 45deg
}
